### ISSUE TITLE
Normalization before rfft and irfft

### ISSUE THREAD

**Issue by beginnerinphysics** [Zhenxing-Dong/Fourier-inspired-neural-module#2]
Hello, Zhenxing,
I am a beginner in this Holography, and I find in rfft2 and irfft2 there's a norm=ortho,
![image](https://github.com/user-attachments/assets/f52b75ad-d6e6-4432-861b-b8d0702d4c2f)
due to the default about these function is no normalization, 
I want to ask, is norm = orthonormal an experiment result, which always make the performance better?
Thanks for the helping

**Comment by Zhenxing-Dong** [comment]
Hi!
In fact, we didn't try different normalizations for FFT in the paper. In my opinion, the role of the Fourier transform is to learn the diffractive information in the hologram generation process. Therefore, I believe that the Fourier-inspired neural module can enhance performance regardless of the normalization.
Of course, you can try different normalization methods to observe their impact on the final results.
